name: Lint and test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Set up virtual environment with uv
        run: uv sync

      - name: Generate Qt resources
        shell: cmd
        run: |
          call update_lupdate_file.bat
          call update_qts.bat
          call compile_qts.bat
          call compile_qrc.bat

      - name: Run Ruff
        run: |
          uv run ruff check src
          uv run ruff check tests

      - name: Run Pyright
        run: |
          uv run pyright src
          uv run pyright tests
        
      - name: Run Pytest
        run: uv run pytest
